apiVersion: v1
kind: Service
metadata:
  name: wls-service
spec:
  type: LoadBalancer
  selector:
    app: wls-app
  ports:
  - name: adminlistenport
    protocol: TCP
    port: 7001
    targetPort: 7001
    nodePort: 31362
  - name: administrationport
    protocol: TCP
    port: 9002
    targetPort: 9002
    nodePort: 31598